[tool.poetry]
name = "arm-preprocessing"
version = "0.1.0"
description = "Implementation of several preprocessing trchniques for Association Rule Mining (ARM)"
authors = ["firefly-cpp <iztok@iztok-jr-fister.eu>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
